[database]
port={{env "GOBANK_DATABASE_PORT"}}
database={{env "GOBANK_DATABASE_NAME"}}
user= {{env "GOBANK_DATABASE_USER"}}
password={{env "GOBANK_DATABASE_PASSWORD"}}
host={{env "GOBANK_DATABASE_HOST"}}