// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: company.queries.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCompanyAccount = `-- name: CreateCompanyAccount :one
INSERT INTO company (annual_revenue ,years_in_business,trade_name ,phone ,
corporate_email ,category ,balance )
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, annual_revenue, years_in_business, trade_name, phone, corporate_email, category, balance
`

type CreateCompanyAccountParams struct {
	AnnualRevenue   pgtype.Numeric `json:"annual_revenue"`
	YearsInBusiness int32          `json:"years_in_business"`
	TradeName       string         `json:"trade_name"`
	Phone           string         `json:"phone"`
	CorporateEmail  string         `json:"corporate_email"`
	Category        string         `json:"category"`
	Balance         pgtype.Numeric `json:"balance"`
}

func (q *Queries) CreateCompanyAccount(ctx context.Context, arg CreateCompanyAccountParams) (Company, error) {
	row := q.db.QueryRow(ctx, createCompanyAccount,
		arg.AnnualRevenue,
		arg.YearsInBusiness,
		arg.TradeName,
		arg.Phone,
		arg.CorporateEmail,
		arg.Category,
		arg.Balance,
	)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.AnnualRevenue,
		&i.YearsInBusiness,
		&i.TradeName,
		&i.Phone,
		&i.CorporateEmail,
		&i.Category,
		&i.Balance,
	)
	return i, err
}

const deleteCompanyAccount = `-- name: DeleteCompanyAccount :exec
DELETE FROM company WHERE id = $1
`

func (q *Queries) DeleteCompanyAccount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCompanyAccount, id)
	return err
}

const getCompanyAcountById = `-- name: GetCompanyAcountById :one
SELECT id, annual_revenue, years_in_business, trade_name, phone, corporate_email, category, balance FROM company WHERE id = $1
`

func (q *Queries) GetCompanyAcountById(ctx context.Context, id uuid.UUID) (Company, error) {
	row := q.db.QueryRow(ctx, getCompanyAcountById, id)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.AnnualRevenue,
		&i.YearsInBusiness,
		&i.TradeName,
		&i.Phone,
		&i.CorporateEmail,
		&i.Category,
		&i.Balance,
	)
	return i, err
}

const updateCompanyBalance = `-- name: UpdateCompanyBalance :exec
UPDATE company SET balance = $1 WHERE id = $2
`

type UpdateCompanyBalanceParams struct {
	Balance pgtype.Numeric `json:"balance"`
	ID      uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateCompanyBalance(ctx context.Context, arg UpdateCompanyBalanceParams) error {
	_, err := q.db.Exec(ctx, updateCompanyBalance, arg.Balance, arg.ID)
	return err
}
