// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Company struct {
	ID              uuid.UUID      `json:"id"`
	AnnualRevenue   pgtype.Numeric `json:"annual_revenue"`
	YearsInBusiness int32          `json:"years_in_business"`
	TradeName       string         `json:"trade_name"`
	Phone           string         `json:"phone"`
	CorporateEmail  string         `json:"corporate_email"`
	Category        string         `json:"category"`
	Balance         pgtype.Numeric `json:"balance"`
}

type Person struct {
	ID            uuid.UUID      `json:"id"`
	MonthlyIncome pgtype.Numeric `json:"monthly_income"`
	Age           int32          `json:"age"`
	FullName      string         `json:"full_name"`
	Phone         string         `json:"phone"`
	Email         string         `json:"email"`
	Category      string         `json:"category"`
	Balance       pgtype.Numeric `json:"balance"`
}
