// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: person.queries.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPersonAccount = `-- name: CreatePersonAccount :one
INSERT INTO person (monthly_income,age,full_name,phone,email,category,balance )
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, monthly_income, age, full_name, phone, email, category, balance
`

type CreatePersonAccountParams struct {
	MonthlyIncome pgtype.Numeric `json:"monthly_income"`
	Age           int32          `json:"age"`
	FullName      string         `json:"full_name"`
	Phone         string         `json:"phone"`
	Email         string         `json:"email"`
	Category      string         `json:"category"`
	Balance       pgtype.Numeric `json:"balance"`
}

func (q *Queries) CreatePersonAccount(ctx context.Context, arg CreatePersonAccountParams) (Person, error) {
	row := q.db.QueryRow(ctx, createPersonAccount,
		arg.MonthlyIncome,
		arg.Age,
		arg.FullName,
		arg.Phone,
		arg.Email,
		arg.Category,
		arg.Balance,
	)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.MonthlyIncome,
		&i.Age,
		&i.FullName,
		&i.Phone,
		&i.Email,
		&i.Category,
		&i.Balance,
	)
	return i, err
}

const deletePersonAccount = `-- name: DeletePersonAccount :exec
DELETE FROM person WHERE id = $1
`

func (q *Queries) DeletePersonAccount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePersonAccount, id)
	return err
}

const getPersonAcountById = `-- name: GetPersonAcountById :one
SELECT id, monthly_income, age, full_name, phone, email, category, balance FROM person WHERE id = $1
`

func (q *Queries) GetPersonAcountById(ctx context.Context, id uuid.UUID) (Person, error) {
	row := q.db.QueryRow(ctx, getPersonAcountById, id)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.MonthlyIncome,
		&i.Age,
		&i.FullName,
		&i.Phone,
		&i.Email,
		&i.Category,
		&i.Balance,
	)
	return i, err
}

const updatePersonBalance = `-- name: UpdatePersonBalance :exec
UPDATE person SET balance = $1 WHERE id = $2
`

type UpdatePersonBalanceParams struct {
	Balance pgtype.Numeric `json:"balance"`
	ID      uuid.UUID      `json:"id"`
}

func (q *Queries) UpdatePersonBalance(ctx context.Context, arg UpdatePersonBalanceParams) error {
	_, err := q.db.Exec(ctx, updatePersonBalance, arg.Balance, arg.ID)
	return err
}
